apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - ../../k8s-specifications
replicas:
  - name: vote
    count: 3
  - name: result
    count: 3
  - name: worker
    count: 3
